routes/web.php
<?php

use App\Http\Controllers\BukuController;
use App\Http\Controllers\LaporanSirkulasiBukuController;
use App\Http\Controllers\SirkulasiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::resource('buku', BukuController::class);
Route::resource('sirkulasi', SirkulasiController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/laporan-index', [LaporanSirkulasiBukuController::class, 'index'])->name('laporan');
Route::post('/sirkulasi/check-book', [SirkulasiController::class, 'checkBook']);
Route::post('/sirkulasi/get-denda', [SirkulasiController::class, 'getDenda']);

app/Http/Controllers/SirkulasiController.php
<?php

namespace App\Http\Controllers;

use App\Models\BukuModel;
use App\Models\SirkulasiModel;
use Carbon\Carbon;
use Illuminate\Http\Request;

class SirkulasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $query = SirkulasiModel::with('buku')->orderBy('sirkulasi.id','DESC');
        
        if (isset($_GET['kode_buku'])) {
            $query->where('kode_buku', 'like', "%".$_GET['kode_buku']."%");
        }

        if (isset($_GET['nbi'])) {
            $query->where('nbi', 'like', "%".$_GET['nbi']."%");
        }

        return view('sirkulasi.data', [
            'data' => $query->get(),
            'request' => $_GET,
            'sum_denda' => $query->sum('denda')
        ]);
    }
    
    public function checkBook(Request $request)
    {
        $kode_buku = $request->kode_buku;
        $sirkulasi = SirkulasiModel::where('kode_buku', $kode_buku)->orderBy('id','DESC')->first();
        return response()->json($sirkulasi);
    }

    public function getDenda(Request $request)
    {

        $toDate = Carbon::parse($request->tanggal_kembali);
        $fromDate = Carbon::parse($request->tanggal_pinjam);
  
        $days = $toDate->diffInDays($fromDate);
        $months = $toDate->diffInMonths($fromDate);
        $years = $toDate->diffInYears($fromDate);

        $denda = 0;

        if ($days > 7) {
            $denda = ( (int) $days - 6) * 1000;
        }

        // return response()->json($days);

        echo $denda;

    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $buku = BukuModel::orderBy('id','desc')->get();
        return view('sirkulasi.form', [
            'buku' => $buku
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        SirkulasiModel::create($request->all());
        return redirect('sirkulasi');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = SirkulasiModel::where('id', $id)->first();
        $buku = BukuModel::orderBy('id','desc')->get();
        return view('sirkulasi.form-edit', [
            'data' => $data,
            'buku' => $buku,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        SirkulasiModel::where('id', $id)->update($request->except('_token','_method'));
        return redirect('sirkulasi');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        SirkulasiModel::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/sirkulasi/data.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Sirkulasi</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="GET">
                        @csrf
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="">Kode Buku</label>
                                    <input type="text" class="form-control" value="{{ $request['kode_buku'] ?? "" }}" name="kode_buku">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="">NBI</label>
                                    <input type="text" class="form-control" value="{{ $request['nbi'] ?? "" }}" name="nbi">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <button class="btn btn-primary mt-4">Cari</button>
                                    <a href="/sirkulasi" class="btn btn-danger mt-4">Reset</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    <hr class="grey">
                    <a href="{{ route('sirkulasi.create') }}" class="btn btn-success">Tambah</a>
                    <table class="table table-bordered table-striped mt-3">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kode buku</th>
                                <th>Judul</th>
                                <th>Jumlah</th>
                                <th>Tanggal pinjam</th>
                                <th>Tanggal kembali</th>
                                <th>NBI</th>
                                <th>Kondisi</th>
                                <th>Denda</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key => $item)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $item->kode_buku }}</td>
                                    <td>{{ $item->buku->judul ?? "" }}</td>
                                    <td>{{ $item->buku->jumlah_halaman ?? "" }}</td>
                                    <td>{{ date('d-m-Y', strtotime($item->tanggal_pinjam)) }}</td>
                                    <td>{{ date('d-m-Y', strtotime($item->tanggal_kembali)) }}</td>
                                    <td>{{ $item->nbi }}</td>
                                    <td>{{ $item->kondisi == 1 ? "Baik" : "Rusak" }}</td>
                                    <td style="text-align: right">{{ "Rp " . number_format($item->denda,0,',','.')  }}</td>
                                    <td>
                                        <form action="{{ route('sirkulasi.destroy', $item->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('sirkulasi.edit', $item->id) }}"
                                                class="btn btn-primary">Edit</a>
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            <tr>
                                <td colspan="8"><b>Denda</b></td>
                                <td class="text-danger" style="text-align: right;font-weight: bold">{{ "Rp " . number_format($sum_denda,0,',','.')  }} </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sirkulasi/form-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Edit Sirkulasi</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('sirkulasi.update', $data->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">NBI</label>
                            <input class="form-control" value="{{ $data->nbi }}" type="text" placeholder="nbi" name="nbi">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tanggal pinjam</label>
                            <input class="form-control" value="{{ $data->tanggal_pinjam }}" type="date" placeholder="tanggal_pinjam" name="tanggal_pinjam">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Kode buku</label>
                            <select name="kode_buku" id="" class="form-control">
                                @foreach ($buku as $item)
                                    <option {{ $data->kode_buku == $item->kode_buku ? "selected" : "" }} value="{{ $item->kode_buku }}">{{ $item->kode_buku }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tanggal kembali</label>
                            <input class="form-control" value="{{ $data->tanggal_kembali }}" type="date" placeholder="tanggal_kembali" name="tanggal_kembali">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Denda</label>
                            <input class="form-control" value="{{ $data->denda }}" type="text" placeholder="denda" name="denda">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Kondisi</label>
                            <select disabled name="kondisi" class="form-control" id="">
                                <option {{ $data->kondisi == 1 ? "selected" : "" }} value="1">Baik</option>
                                <option {{ $data->kondisi == 2 ? "selected" : "" }} value="2">Rusak</option>
                            </select>
                        </div>
                        <button class="btn btn-primary btn-sm mt-3">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sirkulasi/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Tambah Sirkulasi</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('sirkulasi.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="">NBI</label>
                            <input class="form-control" type="text" placeholder="nbi" name="nbi">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tanggal pinjam</label>
                            <input class="form-control tanggal_pinjam" type="date" placeholder="tanggal_pinjam" name="tanggal_pinjam">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Kode buku</label>
                            <select name="kode_buku" id="" class="form-control kode_buku">
                                <option value="" disabled selected>Pilih Buku</option>
                                @foreach ($buku as $item)
                                    <option value="{{ $item->kode_buku }}">{{ $item->kode_buku }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tanggal kembali</label>
                            <input class="form-control tanggal_kembali" type="date" placeholder="tanggal_kembali" name="tanggal_kembali">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Denda</label>
                            <input class="form-control denda" type="text" placeholder="denda" name="denda">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Kondisi</label>
                            <select name="" class="form-control kondisi" id="">
                                <option selected disabled>Pilih Kondisi</option>
                                <option value="1">Baik</option>
                                <option value="2">Rusak</option>
                            </select>
                            <input type="hidden" name="kondisi" class="send-kondisi">
                        </div>
                        <button class="btn btn-primary btn-sm mt-3">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': "{{ csrf_token() }}"
            }
        });
        $(document).ready(function(){
            $('.kode_buku').change(function(){
                var kode_buku = $(this).val();
                $.ajax({
                    url : "{{ url('sirkulasi/check-book') }}",
                    type : "POST",
                    data : {
                        kode_buku : kode_buku
                    },
                    success:function(res){
                        if (res.kondisi) {
                            $('.kondisi').val(res.kondisi);
                            $('.send-kondisi').val(res.kondisi);
                            $('.kondisi').attr('disabled', true);
                        }else{
                            $('.kondisi').val('Pilih Kondisi');
                            $('.kondisi').attr('disabled', false);
                            $('.send-kondisi').val('');
                        }
                    }
                })
            })
            $('.kondisi').change(function(){
                var kondisi = $(this).val();
                $('.send-kondisi').val(kondisi);
            })
            $('.tanggal_kembali').change(function(){
                var tanggal_pinjam = moment($('.tanggal_pinjam').val()).format('Y-MM-DD');
                var tanggal_kembali = moment($(this).val()).format('Y-MM-DD');
                
                $.ajax({
                    url : "{{ url('sirkulasi/get-denda') }}",
                    type : "POST",
                    data : {
                        tanggal_pinjam : tanggal_pinjam,
                        tanggal_kembali : tanggal_kembali
                    },
                    success:function(res){
                        $('.denda').val(res);
                    }
                })
            })
        })
    </script>
@endpush