routes/web.php
<?php

use App\Http\Controllers\BukuController;
use App\Http\Controllers\LaporanSirkulasiBukuController;
use App\Http\Controllers\SirkulasiController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::resource('buku', BukuController::class);
Route::resource('sirkulasi', SirkulasiController::class);
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/laporan-index', [LaporanSirkulasiBukuController::class, 'index'])->name('laporan');
Route::post('/sirkulasi/check-book', [SirkulasiController::class, 'checkBook']);
Route::post('/sirkulasi/get-denda', [SirkulasiController::class, 'getDenda']);

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use App\Models\BukuModel;
use Illuminate\Http\Request;

class BukuController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $query = BukuModel::orderBy('id','DESC');
        
        if (isset($_GET['kode_buku'])) {
            $query->where('kode_buku', 'like', "%".$_GET['kode_buku']."%");
        }

        if (isset($_GET['judul_buku'])) {
            $query->where('judul', 'like', "%".$_GET['judul_buku']."%");
        }

        return view('buku.data', [
            'data' => $query->get(),
            'request' => $_GET
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('buku.form');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        BukuModel::create($request->all());
        return redirect('buku');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = BukuModel::where('id', $id)->first();
        return view('buku.form-edit', [
            'data' => $data
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        BukuModel::where('id', $id)->update($request->except('_token','_method'));
        return redirect('buku');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        BukuModel::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/buku/data.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Buku</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="GET">
                        @csrf
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="">Kode Buku</label>
                                    <input type="text" class="form-control" value="{{ $request['kode_buku'] ?? "" }}" name="kode_buku">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label for="">Judul Buku</label>
                                    <input type="text" class="form-control" value="{{ $request['judul_buku'] ?? "" }}" name="judul_buku">
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <button class="btn btn-primary mt-4">Cari</button>
                                    <a href="/buku" class="btn btn-danger mt-4">Reset</a>
                                </div>
                            </div>
                        </div>
                    </form>
                    <hr class="grey">
                    <a href="{{ route('buku.create') }}" class="btn btn-success">Tambah</a>
                    <table class="table table-bordered table-striped mt-3">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kode buku</th>
                                <th>Judul</th>
                                <th>Pengarang</th>
                                <th>Tahun</th>
                                <th>ISBN</th>
                                <th>jumlah halaman</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($data as $key => $item)
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $item->kode_buku }}</td>
                                    <td>{{ $item->judul }}</td>
                                    <td>{{ $item->pengarang }}</td>
                                    <td>{{ $item->tahun }}</td>
                                    <td>{{ $item->isbn }}</td>
                                    <td>{{ $item->jumlah_halaman }}</td>
                                    <td>
                                        <form action="{{ route('buku.destroy', $item->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('buku.edit', $item->id) }}"
                                                class="btn btn-primary">Edit</a>
                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/buku/form-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Edit Buku</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('buku.update', $data->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="">Kode buku</label>
                            <input type="text" value="{{ $data->kode_buku }}" placeholder="Kode buku" name="kode_buku" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Judul</label>
                            <input type="text" value="{{ $data->judul }}" placeholder="Judul" name="judul" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Pengarang</label>
                            <input type="text" value="{{ $data->pengarang }}" placeholder="Pengarang" name="pengarang" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tahun</label>
                            <input type="text" value="{{ $data->tahun }}" placeholder="Tahun" name="tahun" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">ISBN</label>
                            <input type="text" value="{{ $data->isbn }}" placeholder="ISBN" name="isbn" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">jumlah halaman</label>
                            <input type="text" value="{{ $data->jumlah_halaman }}" placeholder="jumlah halaman" name="jumlah_halaman" class="form-control">
                        </div>
                        <button class="btn btn-primary btn-sm mt-3">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/buku/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="card-title h4">Tambah Buku</span>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="{{ route('buku.store') }}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="">Kode buku</label>
                            <input type="text" placeholder="Kode buku" name="kode_buku" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Judul</label>
                            <input type="text" placeholder="Judul" name="judul" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Pengarang</label>
                            <input type="text" placeholder="Pengarang" name="pengarang" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">Tahun</label>
                            <input type="text" placeholder="Tahun" name="tahun" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">ISBN</label>
                            <input type="text" placeholder="ISBN" name="isbn" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <label for="">jumlah halaman</label>
                            <input type="text" placeholder="jumlah halaman" name="jumlah_halaman" class="form-control">
                        </div>
                        <button class="btn btn-primary btn-sm mt-3">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection